'use strict';
const bundle = JSON.parse(document.getElementById('analysis-data').textContent);
const D = bundle.workspace, H = bundle.index;
const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = n => Number(n).toLocaleString();
const pct = (a,b) => b ? `${(a/b*100).toFixed(1)}%` : 'Unknown (empty denominator)';
const views = {overview:'Overview', findings:'Findings', architecture:'Architecture', impact:'Change impact', coupling:'Boundaries & coupling', evolution:'Evolution', evidence:'Evidence', work:'Work product', scope:'Evidence scope'};
const component = id => D.components.find(c => c.id === id);
const evidence = id => D.evidence.find(e => e.id === id) || (D.changes.baseline_evidence || []).find(e => e.id === id);
const finding = id => D.findings.find(f => f.id === id);
const key = `otterdesk-architecture:${D.repository_id}:${D.id}`;
let state, reviews = [], zoom = 1;
const readRoute = () => {
  const p = new URLSearchParams(location.hash.slice(1));
  return {view: views[p.get('view')] ? p.get('view') : 'overview', q:p.get('q')||'', focus:p.get('focus')||'', tab:p.get('tab')||'', filter:p.get('filter')||''};
};
state = readRoute();
try { reviews = JSON.parse(localStorage.getItem(key+':reviews') || '[]'); } catch { reviews = []; }
function notify(text) {const n=document.getElementById('notice'); n.textContent=text; n.style.display='block'; clearTimeout(notify.timer); notify.timer=setTimeout(()=>n.style.display='none',6000);}
function go(view, extra={}) {state={...state,view,tab:'',filter:'',...extra}; location.hash=new URLSearchParams(state).toString(); render();}
function matches(row) {return !state.q || JSON.stringify(row).toLowerCase().includes(state.q.toLowerCase());}
function scopedFindings() {return D.findings.filter(f => matches(f) && (!state.focus || f.component_ids.includes(state.focus)) && (!state.filter || (state.filter === 'review' ? !['Dismiss','Accept with qualification'].includes(reviewState(f)) : f.status === state.filter)));}
function reviewState(f) {const all=[...f.review_history,...reviews.filter(r=>r.continuity_key===f.continuity_key)];const current=all.filter(r=>r.material_digest===f.material_digest);if(current.length){const actors=new Map(current.map(r=>[r.actor,r.action]));return new Set(actors.values()).size>1?'Reviewers disagree':current[current.length-1].action;}return all.length?'Needs reassessment':f.review_state;}
function badge(text) {return `<span class="status">${esc(text)}</span>`;}
function btn(label,action,id='',cls='') {return `<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${esc(label)}</button>`;}
function card(title,body) {return `<section class="card"><h2>${esc(title)}</h2>${body}</section>`;}
function empty(text) {return `<p class="empty">${esc(text)}</p>`;}
function table(headers,rows) {return rows.length ? `<div class="scroll"><table class="table"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : empty('No matching records in this view.');}
function evlinks(ids) {return `<div class="chips">${ids.map(id=>btn(`${evidence(id)?.path || id}:${evidence(id)?.start_line || '?'}`,'evidence',id)).join('')}</div>`;}
function qualified() {return `<div class="qualification">Source analysis · Runtime behavior and compatibility are unverified. ${esc(D.status)} review; ${esc(D.terminal.stop_reason || 'See task audit')}. Missing evidence remains unknown.</div>`;}
function routeLink(view,label=views[view]) {return `<a href="#view=${view}">${esc(label)}</a>`;}
function scopedPrompts() {return D.improvement_prompts.prompts.filter(p=>matches(p)&&(!state.focus||p.target_files.some(path=>component(state.focus)?.files.includes(path))));}
function promptMarkdown(rows) {return '## Suggested prompts for your coding tool\n\nExpected benefits are proposed, not measured. Copying a prompt does not execute it.\n\n'+rows.map(p=>{const fence='`'.repeat(Math.max(2,...(p.prompt.match(/`+/g)||[]).map(s=>s.length))+1);return `### ${p.mode}: ${p.title}\n\nExpected value: ${p.expected_value}\n\nDesired result: ${p.desired_result}\n\n${fence}text\n${p.prompt.trimEnd()}\n${fence}\n`;}).join('\n');}
function promptCards(rows) {return rows.length?rows.map(p=>`<article class="card handoff"><div class="row">${badge(p.mode)}<small>${esc(p.record_type.replaceAll('_',' '))}</small></div><h3>${esc(p.title)}</h3><p><strong>Why this helps:</strong> ${esc(p.expected_value)}</p><p><strong>Done when:</strong> ${esc(p.desired_result)}</p><small>${esc(p.value_basis)} · ${p.evidence_ids.length} source records${p.omitted_source_records?` · ${p.omitted_source_records} need the full data export`:''}</small><div class="actions">${btn('Copy prompt','copy-prompt',p.id)}${btn('Inspect prompt','prompt',p.id)}</div></article>`).join(''):empty('No matching handoff. Clear filters or inspect the evidence gaps.');}
function promptDetail(p) {return `<p>${esc(p.mode)} · ${esc(p.value_basis)}</p><p>${esc(p.expected_value)}</p><p>Desired result: ${esc(p.desired_result)}</p><label for="coding-prompt">Prompt to paste into your coding tool</label><textarea id="coding-prompt" readonly spellcheck="false">${esc(p.prompt)}</textarea><div class="actions">${btn('Copy prompt','copy-prompt',p.id)}${btn('Export prompt Markdown','export-prompt',p.id)}</div>${evlinks(p.evidence_ids)}`;}
function nextStep() {const rows=scopedPrompts();return card('Your next useful step',`<p>Use the evidence to choose one bounded action, then bring its results back for the next review.</p>${promptCards(rows.slice(0,1))}${btn('View improvement prompts','view','work')}`);}
function findingCards(rows) {return rows.length ? rows.map(f=>`<article class="card"><div class="row"><small>${esc(f.id)} · Revision ${f.revision}</small>${badge(reviewState(f))}</div><h3>${esc(f.statement)}</h3><p>${esc(f.confidence_rationale)}</p><small>${esc(f.basis)} · ${esc(f.status)} · Resolution: ${esc(f.resolution_state)}</small><div class="actions">${btn('Inspect finding','finding',f.id)}${btn('Review','review',f.id)}</div></article>`).join('') : empty('No supported findings were retained. This does not establish architectural health.');}
function tiles() {return `<div class="tiles">${[
  ['Findings need review', D.findings.filter(f=>!['Dismiss','Accept with qualification'].includes(reviewState(f))).length,'review'],
  ['Captured code files',D.files.length,'files'],['Evidence gaps',D.gaps.length,'gaps'],['Proposed work packages',D.work_packages.length,'packages']
].map(([name,n,id])=>`<button class="tile" data-action="tile" data-id="${id}"><small>${name}</small><strong>${fmt(n)}</strong><small>Inspect counted records →</small></button>`).join('')}</div>`;}
function overview() {return qualified()+nextStep()+tiles()+`<div class="grid">${card('Decisions to review',`<p>${esc(D.executive)}</p>${findingCards(D.findings.slice(0,3))}${btn('View findings','view','findings')}`)}${card('Architecture in focus',graph()+`<p class="legend">Directory groupings · Captured module references · No deployment claim</p>${btn('Explore architecture','view','architecture')}`)}${card('Validation still needed',`<p>These are proposed checks. Reviewed repository tests were not executed.</p>${table(['Question','Execution'],D.checks.slice(0,6).map(c=>[btn(c.question,'check',c.id),badge(c.execution_status)]))}${btn('View validation plan','tab','impact:validation')}`)}${card('Since the previous snapshot',D.changes.status==='available' ? `<p>${D.changes.files.length} source paths have different captured hashes.</p><p>${D.changes.findings.length} finding assessments changed.</p>${btn('Compare snapshots','view','evolution')}` : empty(D.changes.reason))}</div>`;}
function graph() {
  const all=D.components.filter(c=>matches(c));
  const chosen=state.focus ? all.filter(c=>c.id===state.focus || D.component_relations.some(r=>(r.source===state.focus&&r.target===c.id)||(r.target===state.focus&&r.source===c.id))) : all;
  const nodes=chosen.slice(0,24), included=new Set(nodes.map(n=>n.id));
  const edges=D.component_relations.filter(r=>included.has(r.source)&&included.has(r.target)&&r.source!==r.target).slice(0,70);
  const pos=new Map(nodes.map((n,i)=>[n.id,{x:25+(i%3)*245,y:25+Math.floor(i/3)*110}]));
  const height=Math.max(180,Math.ceil(nodes.length/3)*110+30);
  if(!nodes.length) return empty('No matching component groups.');
  return `<div class="actions">${btn('−','zoom','out')}${btn('+','zoom','in')}${btn('Reset zoom','zoom','reset')}</div><p class="legend">Showing ${nodes.length}/${chosen.length} matching groups and ${edges.length} selected links. All relationships remain available in the table.</p><div class="graph"><svg viewBox="0 0 760 ${height}" role="group" aria-label="Directory dependency map"><defs><marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#91abba"/></marker></defs><g id="scene" transform="scale(${zoom})">${edges.map(e=>{const a=pos.get(e.source),b=pos.get(e.target);const path=`M${a.x+200},${a.y+34} C${a.x+235},${a.y+34} ${b.x-25},${b.y+34} ${b.x},${b.y+34}`;return `<g role="button" tabindex="0" data-action="edge-group" data-id="${e.id}" aria-label="${esc(component(e.source).name)} refers to ${esc(component(e.target).name)}, ${e.source_site_count} captured source spans"><path class="edge" d="${path}" marker-end="url(#arrow)"/><path class="hit" d="${path}"/></g>`;}).join('')}${nodes.map(n=>{const p=pos.get(n.id);return `<g role="button" tabindex="0" data-action="component" data-id="${n.id}" aria-label="${esc(n.name)}"><rect class="node" x="${p.x}" y="${p.y}" width="200" height="70" rx="9"/><text x="${p.x+12}" y="${p.y+28}">${esc(n.name.length>24?n.name.slice(0,23)+'…':n.name)}</text><text x="${p.x+12}" y="${p.y+50}">${n.files.length} files · ${n.finding_ids.length} findings</text></g>`;}).join('')}</g></svg></div>`;
}
function architecture() {return `<div class="grid">${card('Explore the source architecture',graph())}${card('Component profiles',`<p class="muted">Grouping basis: directory paths. Responsibilities and deployment boundaries require review.</p>${table(['Component','Files','Findings'],D.components.filter(matches).map(c=>[btn(c.name,'component',c.id),fmt(c.files.length),fmt(c.finding_ids.length)]))}`)}<div class="full">${card('Dependency records',relationTable(D.relations.filter(e=>matches(e)&&(!state.focus||e.source_component===state.focus||e.target_component===state.focus))))}</div></div>`;}
function relationTable(edges) {return table(['Referring module','Referenced module','Basis / scope','Exact sources'],edges.map(e=>[esc(e.source),esc(e.target),`${badge(e.basis)} ${badge(e.scope)}<p>${esc(e.classification)}</p>`,evlinks(e.evidence_ids)]));}
function findings() {return `<div class="toolbar"><label for="finding-filter">Assessment</label><select id="finding-filter"><option value="">All retained findings</option>${['review','provisional','supported','contested'].map(v=>`<option value="${v}" ${state.filter===v?'selected':''}>${v==='review'?'Needs review':v}</option>`).join('')}</select><small>${scopedFindings().length}/${D.findings.length} findings shown</small></div>`+findingCards(scopedFindings());}
function tabs(options) {return `<div class="tabs">${options.map(([id,label])=>`<button data-action="tab-local" data-id="${id}" aria-pressed="${(state.tab||options[0][0])===id}">${label}</button>`).join('')}</div>`;}
function impact() {
  const tab=state.tab||'changes';
  let body;
  if(tab==='validation') body=card('Validation plan',`<p>Static test presence is not an executed check. Every generated check below remains not run.</p>${table(['Question / check','Method','Execution'],D.checks.filter(matches).map(c=>[btn(c.question,'check',c.id),esc(c.method),badge(c.execution_status)]))}`);
  else if(tab==='paths') body=card('Dependency impact paths',`<p>These paths use the union of held baseline and candidate static references. Connected does not mean broken.</p><p>Bounds: 100 changed roots, four hops, 128 nodes per root. ${D.changes.omitted_changed_roots||0} roots omitted; ${(D.changes.frontiers||[]).length} unresolved frontier records.</p>${table(['Changed path','Dependent path','Assessment','Path'],D.changes.impacts.filter(matches).map((r,i)=>[esc(r.changed_path),esc(r.dependent_path),`${esc(r.classification)}<p>${esc(r.behavior)}</p>`,btn('Inspect path','impact-path',String(D.changes.impacts.indexOf(r)))]))}`);
  else body=card('Captured source changes',D.changes.status==='available' ? `<p>${esc(D.changes.baseline_definition)}</p><p>Scope ${D.changes.scope_comparable?'matches':'changed; counts are not directly comparable'}. Analysis configuration ${D.changes.analysis_comparable?'matches':'changed'}.</p>${table(['Path','Change','Source identity'],D.changes.files.filter(matches).map((f,i)=>[btn(f.path,'change',String(D.changes.files.indexOf(f))),esc(f.kind),`<code>${esc(f.after_sha256||f.before_sha256)}</code>`]))}` : empty(D.changes.reason));
  return tabs([['changes','Source changes'],['paths','Impact paths'],['validation','Validation plan']])+`<div class="qualification">Contract compatibility, end-to-end workflows and runtime failures need source-matched scenario evidence. No check was run by this viewer.</div>`+body;
}
function matrix(co=false) {
  const all=D.components.filter(matches), cs=all.slice(0,30);
  const counts=new Map();
  if(!co) for(const r of D.component_relations) {const key=r.source+'|'+r.target;counts.set(key,(counts.get(key)||0)+r.source_site_count);}
  const changes=D.history.change_sets||[];
  const sets=new Map(cs.map(c=>[c.id,new Set(changes.filter(x=>x.paths.some(p=>c.files.includes(p))).map(x=>x.id))]));
  return `<p class="legend">${co?'Cells count shared non-merge commits; diagonal is commits touching the group.':'Row refers to column; cells count distinct captured source spans.'} Showing ${cs.length}/${all.length} matching groups.</p><div class="scroll"><table class="matrix"><thead><tr><th scope="col">${co?'Touches both':'Row → column'}</th>${cs.map(c=>`<th title="${esc(c.name)}" scope="col">${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${cs.map(a=>`<tr><th scope="row" title="${esc(a.name)}">${esc(a.name)}</th>${cs.map(b=>{const n=co?[...sets.get(a.id)].filter(id=>sets.get(b.id).has(id)).length:(counts.get(a.id+'|'+b.id)||0);return `<td><button data-action="${co?'cochange':'dependency-pair'}" data-a="${a.id}" data-b="${b.id}" style="background:rgba(0,135,125,${.07+Math.min(n,20)/30})" aria-label="${esc(a.name)} to ${esc(b.name)}: ${n} ${co?'commits':'source spans'}">${n}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function coupling() {
  const tab=state.tab||'dependencies'; let body;
  if(tab==='history') body=D.history.status==='available' ? card('Which groups changed together?',`<p>${esc(D.history.scope)} · Limit ${D.history.commit_limit} commits · Anchored at <code>${esc(D.history.anchor)}</code></p>${matrix(true)}<div class="qualification">Co-change is an investigation clue. It is not a hidden dependency, a defect, or a failure probability. Mechanical changes are not automatically classified.</div>`) : card('Co-change history',empty(D.history.reason));
  else if(tab==='cycles') body=card('Static cyclic module groups',`<p>${D.cycles.length} strongly connected groups in the captured module dependency graph. Test and application references remain classified by source path; type-only semantics are unknown. A static cycle does not establish deadlock.</p>${D.cycles.map((c,i)=>btn(c.join(' → '),'cycle',String(i),'listbutton')).join('')||empty('No cycle found in captured module edges. Unsupported and dynamic dependencies remain outside this result.')}`);
  else if(tab==='hotspots') body=card('Structural investigation candidates',table(['Directory group','Source lines','Incoming / outgoing links','Historical commits'],D.components.filter(matches).map(c=>[btn(c.name,'component',c.id),fmt(D.files.filter(f=>f.component_id===c.id).reduce((a,f)=>a+f.lines,0)),`${D.component_relations.filter(r=>r.target===c.id).length} / ${D.component_relations.filter(r=>r.source===c.id).length}`,D.history.status==='available'?fmt(D.history.change_sets.filter(x=>x.paths.some(p=>c.files.includes(p))).length):'Unknown']))+`<p class="muted">Size and connectivity are separate measurements. They are not severity, complexity or engineering effort scores.</p>`);
  else body=card('Captured dependency matrix',matrix()+`<p class="muted">No approved policy register was supplied. A dependency does not alone establish a boundary violation.</p>`);
  return tabs([['dependencies','Dependency matrix'],['history','Co-change history'],['cycles','Dependency cycles'],['hotspots','Structural hotspots']])+body;
}
function evolution() {return card('Retained snapshots',`<p>${esc(D.history_mode)} · Snapshots accumulate without erasing earlier evidence. A disappeared finding is not automatically fixed.</p>${table(['Snapshot / run','Capture time','Status','Files / findings'],H.snapshots.map(s=>[`<a href="${bundle.historical?'':'snapshots/'}${s.id}.html#view=evolution">${esc(s.snapshot_id)}</a><small>${esc(s.run_id)}</small>`,esc(s.captured_at),badge(s.status),`${s.files} / ${s.findings}`]))}`)+card('Assessment changes',D.changes.status==='available'?table(['Finding','Change','Qualification'],D.changes.findings.map(f=>[esc(f.id),esc(f.kind),esc(f.note)])):empty(D.changes.reason));}
function evidencePage() {const rows=D.evidence.filter(e=>matches(e)&&(!state.focus||component(state.focus)?.files.includes(e.path)));return card('Exact retained source records',`<p>${rows.length}/${D.evidence.length} records shown. Excerpts come from captured source; they do not execute. Hashes identify complete files.</p>${table(['Source','Lines','Snapshot / revision'],rows.map(e=>[btn(e.path,'evidence',e.id),`${e.start_line}–${e.end_line}`,`<code>${esc(e.revision||e.snapshot)}</code>`]))}`)+card('Open evidence gaps',table(['Question','Missing evidence','Closure'],D.gaps.filter(matches).map(g=>[btn(g.question,'gap',g.id),esc(g.missing),esc(g.closure)])));}
function workRecords() {return `<div class="grid">${card('Proposed recommendations',table(['Action','Alternatives','Next decision'],D.recommendations.filter(matches).map(r=>[btn(r.action,'recommendation',r.id),esc(r.alternatives),esc(r.next_decision)])))}${card('Engineering work packages',D.work_packages.filter(matches).map(w=>`<article class="card"><h3>${esc(w.goal)}</h3><p>${esc(w.constraints)}</p>${badge('Proposed · Implementation requires separate scope')}<div class="actions">${btn('Inspect package','package',w.id)}${btn('Export Markdown','export-package',w.id)}</div></article>`).join('')||empty('No supported work package was produced. Inspect the evidence gaps before proposing an implementation.'))}</div>${card('Review decisions',`<p>Review drafts belong to this browser and exact evidence revision. Export them and set <code>inputs.payload.review_file</code> on the next run to retain them in Job history.</p>${btn('Export review decisions','export-reviews')}${table(['Finding','Actor / time','Decision / rationale'],[...D.findings.flatMap(f=>f.review_history),...reviews].map(r=>[esc(r.continuity_key),`${esc(r.actor)}<p>${esc(r.at)}</p>`,`${badge(r.action)}<p>${esc(r.rationale)}</p>`]))}`)}`;}
function work() {const rows=scopedPrompts().filter(p=>!state.tab||p.mode===state.tab);return card('Improve the architecture',`<p>Take a source-linked next step in your coding tool. Investigate and plan first; implementation prompts appear only for supported, scoped work packages.</p><div class="toolbar"><label for="prompt-mode">Prompt type</label><select id="prompt-mode"><option value="">All next steps</option>${['Investigate','Plan','Implement','Verify'].map(m=>`<option ${state.tab===m?'selected':''}>${m}</option>`).join('')}</select>${btn('Export improvement prompts','export-prompts')}<small>Showing ${Math.min(rows.length,32)}/${rows.length} matching prompts. Search to find a specific record.</small></div>${promptCards(rows.slice(0,32))}<p class="muted">${D.improvement_prompts.coverage.omitted} further handoffs omitted at the publication limit; full records remain in the data export.</p>`)+workRecords();}
function scope() {return card('Source and analysis identity',`<p>Snapshot <code>${esc(D.snapshot_id)}</code></p><p>Git revision <code>${esc(D.revision||'Unavailable')}</code></p><p>Captured bytes identity <code>${D.source_identity}</code></p><p>Analysis configuration <code>${D.config_identity}</code></p><p>${esc(D.execution.network)}</p><p>Model: ${esc(D.execution.model||'See review configuration')}</p><p>${esc(D.execution.source_execution)}</p>`)+card('Capabilities by language',table(['Language','Captured / structural files','Parsing','Results'],D.capabilities.map(c=>[esc(c.language),`${c.files} / ${c.structural_files}`,esc(c.parsing),`${c.runtime} runtime · Tests ${c.test_results}`])))+card('Captured code inventory',table(['Path','Language / scope','SHA-256'],D.files.filter(matches).map(f=>[`<span class="truncate" title="${esc(f.path)}">${esc(f.path)}</span>`,`${esc(f.language)} · ${esc(f.scope)}`,`<code>${f.sha256}</code>`])))+card('Coverage and limitations',`<p>${esc(JSON.stringify(D.source_scope.capture_limits))}</p><p>Exclusions: ${esc(D.source_scope.exclusions.join(', '))}</p>${[...D.limitations,...D.structural_limits].map(l=>`<p>• ${esc(l)}</p>`).join('')}${table(['Report aspect','Coverage','Limitations'],D.coverage.aspects.filter(matches).map(a=>[esc(a.title),badge(a.coverage),esc(a.limitations.join('; '))]))}`);}
function render() {
  const content={overview,findings,architecture,impact,coupling,evolution,evidence:evidencePage,work,scope}[state.view]();
  document.getElementById('app').innerHTML=`<aside><div class="brand">OtterDesk</div><nav class="nav" aria-label="Investigation">${Object.entries(views).map(([id,label])=>`<a href="#view=${id}" ${state.view===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="worker">Architecture Advisor<br>${esc(D.status)} · Source review<br>Read-only code · Saved analysis</div></aside><div class="layout"><header class="top"><strong title="${esc(D.repository)}">${esc(D.repository_label)}</strong>${bundle.historical?'<a href="../index.html">Open latest workspace</a>':''}<label for="snapshot" class="muted">Snapshot</label><select id="snapshot">${H.snapshots.map(s=>`<option value="${s.id}" ${s.id===D.id?'selected':''}>${esc(s.captured_at)} · ${esc(s.status)} · ${esc(s.snapshot_id.slice(0,8))}</option>`).join('')}</select></header><main id="content"><div class="head"><div><small>Architecture investigation</small><h1>${views[state.view]}</h1><p class="muted">${esc(D.goal)}</p></div><div class="actions">${btn('Save view','save-view')}${btn('Restore saved view','restore-view')}${btn('Create briefing','briefing','','primary')}</div></div><div class="context"><span>Snapshot <code title="${D.snapshot_id}">${D.snapshot_id.slice(0,12)}</code></span><span>Revision <code title="${esc(D.revision||'No Git revision')}">${esc(D.revision?.slice(0,12)||'Unavailable')}</code></span><span>${D.files.length} captured files</span><span>Deployment unverified · ${esc(D.worktree_state)}</span><span>${esc(D.history_mode)}</span></div><div class="toolbar"><label for="search">Search records</label><input id="search" value="${esc(state.q)}" placeholder="Finding, path, evidence or component"><label for="focus">Component filter</label><select id="focus"><option value="">All captured groups</option>${D.components.map(c=>`<option value="${c.id}" ${state.focus===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select>${state.focus?btn('Clear focus','clear-focus'):''}</div>${state.q||state.focus?'<p class="notice">Filtered navigation; findings retain their supporting evidence and counterevidence in details.</p>':''}${content}<footer class="foot">Evidence-backed drafts · No repository code runs from this page · Offline, no CDN · Source scope and unknowns remain visible</footer></main></div>`;
}
function modal(title,body) {const d=document.getElementById('details');d.innerHTML=`${btn('Close','close','','close')}<h2>${esc(title)}</h2>${body}`;if(!d.open)d.showModal();}
function sourceDetail(e) {if(!e)return empty('Exact source unavailable — verification required.');return `<p><code>${esc(e.path)}:${e.start_line}–${e.end_line}</code></p><p>Snapshot <code>${esc(e.snapshot)}</code> · Revision <code>${esc(e.revision||'Unavailable')}</code></p><p>File SHA-256 <code>${e.sha256}</code></p><pre>${esc(e.excerpt)}</pre>${btn('Copy citation','copy-citation',e.id)}`;}
function findingContext(f) {return `<p>${esc(f.statement)}</p>${badge(f.status)} ${badge(reviewState(f))}<p>Basis: ${esc(f.basis)}. Confidence: ${esc(f.confidence)}. ${esc(f.confidence_rationale)}</p>${f.architecture?Object.entries(f.architecture).map(([k,v])=>`<h3>${esc(k.replaceAll('_',' '))}</h3><p>${esc(v)}</p>`).join(''):'<p>Detailed mechanism and closure conditions were not recorded in this finding revision.</p>'}<h3>Supporting source</h3>${evlinks(f.evidence_ids)}<h3>Counterevidence (${esc(f.counterevidence_status)})</h3><p>${esc(f.counterevidence)}</p>${evlinks(f.counterevidence_ids)}<h3>Next decision</h3>${D.recommendations.filter(r=>f.recommendation_ids.includes(r.id)).map(r=>`<p>${esc(r.action)}</p><p>Alternatives: ${esc(r.alternatives)}</p><p>Validation: ${esc(r.validation)}</p>`).join('')||'<p>Review the evidence and request the missing check before accepting this assessment.</p>'}<p>Resolution: ${esc(f.resolution_state)}. Accepting analysis does not establish remediation.</p>${btn('Review finding','review',f.id)}`;}
function findingDetail(f) {return findingContext(f)+card('Prompts for this decision',promptCards(D.improvement_prompts.prompts.filter(p=>p.finding_ids.includes(f.id))));}
function showPair(a,b) {
  const commits=D.history.change_sets||[];
  const left=new Set(commits.filter(c=>c.paths.some(p=>component(a).files.includes(p))).map(c=>c.id));
  const right=new Set(commits.filter(c=>c.paths.some(p=>component(b).files.includes(p))).map(c=>c.id));
  const shared=commits.filter(c=>left.has(c.id)&&right.has(c.id));
  const union=new Set([...left,...right]);
  modal(`${component(a).name} ↔ ${component(b).name}`,`<p>Unit: captured non-merge commits touching current captured paths. Mechanical changes are not classified or excluded.</p><div class="pair"><div class="metric">${pct(shared.length,left.size)}<small>${shared.length}/${left.size} · Second given first</small></div><div class="metric">${pct(shared.length,right.size)}<small>${shared.length}/${right.size} · First given second</small></div><div class="metric">${pct(shared.length,union.size)}<small>${shared.length}/${union.size} · Union overlap</small></div></div>${table(['Commit','Time','Captured changed paths'],shared.map(c=>[`<code>${esc(c.id)}</code>`,esc(c.at),c.paths.map(p=>esc(p)).join('<br>')]))}${btn('Export matching changes','export-pair',a+'|'+b)}<p>Correlation does not establish causation or defect severity.</p>`);
}
function download(name,text,type='text/plain') {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function packageMarkdown(w) {return `# Proposed work: ${w.goal}\n\nSnapshot: ${D.snapshot_id}\nRevision: ${D.revision||'unavailable'}\n\n${['goal','files','constraints','non_goals','migration_steps','required_tests','acceptance','stop_conditions','approval_status'].map(k=>`## ${k.replaceAll('_',' ')}\n\n${typeof w[k]==='object'?JSON.stringify(w[k],null,2):w[k]||'Unknown'}`).join('\n\n')}\n\n## Exact evidence\n\n${w.evidence_ids.map(id=>{const e=evidence(id);return e?`${e.path}:${e.start_line}-${e.end_line}; SHA-256 ${e.sha256}\n${e.excerpt}`:`${id}: unavailable`}).join('\n\n')}\n\nNo implementation is authorized by exporting this proposal. Suggested tests have not run.\n`+promptMarkdown(D.improvement_prompts.prompts.filter(p=>p.record_type==='work_package'&&p.record_id===w.id));}
function briefing() {const rows=scopedFindings();return `# Architecture briefing\n\nSnapshot: ${D.snapshot_id}\nRevision: ${D.revision||'unavailable'}\nStatus: ${D.status}\nGoal: ${D.goal}\nFilter: ${JSON.stringify(state)}\n\n${D.executive}\n\n${rows.map(f=>`## ${f.statement}\n\n${f.confidence_rationale}\nBasis: ${f.basis}; review: ${reviewState(f)}; resolution: ${f.resolution_state}.\nCounterevidence (${f.counterevidence_status}): ${f.counterevidence}\n${[...f.evidence_ids,...f.counterevidence_ids].map(id=>{const e=evidence(id);return `${id}: ${e.path}:${e.start_line}-${e.end_line}; SHA-256 ${e.sha256}`}).join('\n')}`).join('\n\n')}\n\n## Qualifications\n\n${D.limitations.join('\n')}\n\nRuntime and compatibility remain unverified. Proposed checks are not executed results.\n`+promptMarkdown(scopedPrompts());}
async function action(el) {
  const id=el.dataset.id, act=el.dataset.action;
  if(act==='view')go(id);
  if(act==='prompt'){const p=D.improvement_prompts.prompts.find(p=>p.id===id);modal(p.mode+': '+p.title,promptDetail(p));}
  if(act==='copy-prompt'){const p=D.improvement_prompts.prompts.find(p=>p.id===id);try{await navigator.clipboard.writeText(p.prompt);notify('Prompt copied. Paste it into your coding tool.');}catch{modal(p.mode+': '+p.title,promptDetail(p));const text=document.getElementById('coding-prompt');text.focus();text.select();notify('Clipboard unavailable. Copy the selected prompt.');}}
  if(act==='export-prompt')download('architecture-'+id+'.md',promptMarkdown(D.improvement_prompts.prompts.filter(p=>p.id===id)),'text/markdown');
  if(act==='export-prompts')download('architecture-improvement-prompts.md',promptMarkdown(scopedPrompts().filter(p=>!state.tab||p.mode===state.tab)),'text/markdown');
  if(act==='tile')go(id==='review'?'findings':id==='files'?'scope':id==='gaps'?'evidence':'work',{filter:id==='review'?'review':''});
  if(act==='tab') {const [view,tab]=id.split(':');go(view,{tab});}
  if(act==='tab-local')go(state.view,{tab:id});
  if(act==='clear-focus')go(state.view,{focus:''});
  if(act==='component') {const c=component(id);modal(c.name,`<p>${esc(c.basis)} · ${esc(c.responsibility)}</p><p>Ownership: ${esc(c.owner)} · Deployment: ${esc(c.deployment)}</p>${btn('Apply component filter','apply-focus',id)}${table(['Captured paths'],c.files.map(p=>[esc(p)]))}${findingCards(D.findings.filter(f=>c.finding_ids.includes(f.id)))}`);}
  if(act==='apply-focus'){document.getElementById('details').close();go('architecture',{focus:id});}
  if(act==='evidence')modal('Exact captured source',sourceDetail(evidence(id)));
  if(act==='finding')modal('Review architecture finding',findingDetail(finding(id)));
  if(act==='edge-group'){const r=D.component_relations.find(r=>r.id===id);modal('Captured dependency sources',relationTable(D.relations.filter(e=>r.relation_ids.includes(e.id))));}
  if(act==='dependency-pair')modal('Matching dependency sources',relationTable(D.relations.filter(r=>r.source_component===el.dataset.a&&r.target_component===el.dataset.b)));
  if(act==='cycle'){const c=D.cycles[Number(id)];modal('Static strongly connected group',`<p>${esc(c.join(' → '))}</p><p>One cyclic group, not a runtime deadlock. Review all internal edges.</p>${relationTable(D.relations.filter(r=>c.includes(r.source)&&c.includes(r.target)))}`);}
  if(act==='cochange')showPair(el.dataset.a,el.dataset.b);
  if(act==='export-pair'){const [a,b]=id.split('|');const rows=D.history.change_sets.filter(c=>c.paths.some(p=>component(a).files.includes(p))&&c.paths.some(p=>component(b).files.includes(p)));download('matching-change-sets.json',JSON.stringify({snapshot:D.snapshot_id,anchor:D.history.anchor,unit:'non-merge commits',matching:rows},null,2),'application/json');}
  if(act==='gap'){const g=D.gaps.find(g=>g.id===id);modal('Evidence gap',`<h3>${esc(g.question)}</h3><p>Missing: ${esc(g.missing)}</p><p>Closure: ${esc(g.closure)}</p>${g.check_id?btn('Inspect proposed check','check',g.check_id):''}`);}
  if(act==='check'){const c=D.checks.find(c=>c.id===id);modal('Proposed validation check',`<h3>${esc(c.question)}</h3>${badge(c.execution_status)}<p>Method: ${esc(c.method)}</p><p>Required input: ${esc(c.required_input)}</p><p>Acceptance: ${esc(c.acceptance)}</p>`);}
  if(act==='recommendation'){const r=D.recommendations.find(r=>r.id===id);modal('Proposed recommendation',Object.entries(r).map(([k,v])=>`<h3>${esc(k.replaceAll('_',' '))}</h3><p>${esc(typeof v==='object'?JSON.stringify(v):v)}</p>`).join(''));}
  if(act==='package'){const w=D.work_packages.find(w=>w.id===id);modal('Proposed work package',promptCards(D.improvement_prompts.prompts.filter(p=>p.record_type==='work_package'&&p.record_id===id))+`<pre>${esc(packageMarkdown(w))}</pre>${btn('Export Markdown','export-package',id)}`);}
  if(act==='export-package')download('work-package-'+id+'.md',packageMarkdown(D.work_packages.find(w=>w.id===id)),'text/markdown');
  if(act==='change'){const c=D.changes.files[Number(id)];modal(c.kind+': '+c.path,`<div class="grid">${card('Baseline captured identity',`<code>${esc(c.before_sha256||'Absent from captured scope')}</code>${c.before_evidence.map(e=>sourceDetail(e)).join('')||empty('No retained cited baseline excerpt. Full semantic diff unavailable.')}`)}${card('Candidate captured identity',`<code>${esc(c.after_sha256||'Absent from captured scope')}</code>${evlinks(c.after_evidence_ids)}`)}</div><p>These are exact cited excerpts, not a reconstructed full source diff.</p>`);}
  if(act==='impact-path'){const r=D.changes.impacts[Number(id)];modal('Structural dependency path',`<p>${esc(r.dependent_path)} → ${esc(r.changed_path)}</p><p>${esc(r.classification)} · ${esc(r.behavior)}</p>${r.path.map(e=>`<div class="path"><h3>${esc(e.source)} → ${esc(e.target)}</h3><p>${esc(e.basis)} · ${esc(e.scope)}</p>${evlinks(e.evidence_ids)}</div>`).join('')}`);}
  if(act==='zoom'){zoom=id==='reset'?1:Math.min(2,Math.max(.5,zoom+(id==='in'?.2:-.2)));render();}
  if(act==='close')document.getElementById('details').close();
  if(act==='briefing')download('architecture-briefing.md',briefing(),'text/markdown');
  if(act==='save-view'){try{localStorage.setItem(key+':view',JSON.stringify(state));notify('View saved in this browser for this snapshot.');}catch{notify('Browser storage unavailable. Bookmark this page to retain the view.');}}
  if(act==='restore-view'){try{const saved=JSON.parse(localStorage.getItem(key+':view')||'null');if(saved&&views[saved.view])go(saved.view,saved);else notify('No saved view for this snapshot.');}catch{notify('Saved view could not be loaded.');}}
  if(act==='review'){const f=finding(id);modal('Record a review draft',`<p>${esc(f.statement)}</p><p>This changes review state only. Source and resolution remain unchanged.</p><label for="actor">Reviewer name</label><input id="actor" maxlength="200"><label for="review-action">Decision</label><select id="review-action">${['Accept with qualification','Revise','Request evidence','Dismiss','Reopen'].map(a=>`<option>${a}</option>`).join('')}</select><label for="rationale">Rationale and revised wording where needed</label><textarea id="rationale" maxlength="4000"></textarea>${btn('Save review draft','save-review',id,'primary')}`);}
  if(act==='save-review'){const actor=document.getElementById('actor').value.trim(),rationale=document.getElementById('rationale').value.trim();if(!actor||!rationale){notify('Enter reviewer name and rationale.');return;}const f=finding(id);reviews.push({id:crypto.randomUUID(),continuity_key:f.continuity_key,material_digest:f.material_digest,actor,at:new Date().toISOString(),rationale,action:document.getElementById('review-action').value});try{localStorage.setItem(key+':reviews',JSON.stringify(reviews));}catch{notify('Draft is in memory only. Export decisions to retain it.');}document.getElementById('details').close();render();}
  if(act==='export-reviews')download('architecture-reviews.json',JSON.stringify({schema_version:'mn.architecture.reviews.v1',repository_id:D.repository_id,snapshot:D.id,decisions:[...new Map([...D.findings.flatMap(f=>f.review_history),...reviews].map(r=>[r.id,r])).values()]},null,2),'application/json');
  if(act==='copy-citation'){const e=evidence(id);try{await navigator.clipboard.writeText(`${e.path}:${e.start_line}-${e.end_line}; snapshot ${e.snapshot}; revision ${e.revision||'unavailable'}; SHA-256 ${e.sha256}`);notify('Citation copied.');}catch{notify('Clipboard unavailable. Source identity remains visible in the detail panel.');}}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el).catch(()=>notify('Could not complete this action. Inspect the retained data and try again.'));});
document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('g[role=button]')){e.preventDefault();action(e.target);}});
document.addEventListener('change',e=>{
  if(e.target.id==='snapshot')location.href=(bundle.historical?'':'snapshots/')+e.target.value+'.html'+location.hash;
  if(e.target.id==='prompt-mode')go('work',{tab:e.target.value});
  if(e.target.id==='focus')go(state.view,{focus:e.target.value});
  if(e.target.id==='finding-filter')go('findings',{filter:e.target.value});
});
document.addEventListener('input',e=>{if(e.target.id==='search'){const position=e.target.selectionStart;state.q=e.target.value;history.replaceState(null,'','#'+new URLSearchParams(state));render();const s=document.getElementById('search');s.focus();s.setSelectionRange(position,position);}});
window.addEventListener('hashchange',()=>{state=readRoute();render();});
render();
