from __future__ import annotations

from otterdesk_blueprint_suite import (
    test_cctv_operator_declares_domain_agent_aliases,
    test_cctv_operator_declares_otterdesk_chat_system_prompt,
    test_cctv_operator_detector_script_compiles_with_shared_helper_import,
    test_cctv_operator_default_folder_validates_from_blueprint_root,
    test_cctv_operator_folder_validator_accepts_supported_recordings,
    test_cctv_operator_folder_validator_rejects_empty_folder,
    test_cctv_operator_stream_validator_probes_rtsp_and_rtmp,
    test_cctv_operator_stream_validator_rejects_non_stream_uri,
    test_cctv_operator_uses_hostlocal_nvidia_media_worker,
    test_cctv_operator_uses_shared_runtime_web_ui_without_compose_or_media_bridge,
)
