from __future__ import annotations

from otterdesk_blueprint_suite import (
    test_otterdesk_batch_workflows_complete_with_shared_runner,
    test_otterdesk_workflow_runtime_executes_manifest_steps,
    test_optional_tax_branch_can_finish_partial_and_still_merge,
    test_personal_income_tax_expert_runtime_branch_step_exits_without_full_packet,
    test_personal_income_tax_expert_runtime_branch_step_infers_agent_id_without_full_packet,
    test_personal_income_tax_expert_runtime_branch_step_infers_message_destination,
    test_personal_income_tax_expert_runtime_topology_mirrors_workflow_graph,
    test_static_graph_validation_rejects_cycles_and_overlapping_parallel_outputs,
    test_tax_workflow_compiles_as_static_fork_join_graph,
)
