"""Shared bounded public-research records, configuration, and tool policy."""

from __future__ import annotations

from .common import *
from .intake import redactor, slugify
from .runtime_tools import (
    append_event,
    observed_operation,
    quick_test_mode_enabled,
    stable_text_hash,
)

def _research_observer(run_dir: Path | None):
    def observe(event_type: str, payload: dict[str, Any]) -> None:
        if run_dir is None:
            return
        append_event(run_dir, event_type, payload)

    return observe

def _configured_research(company: str, internet: dict[str, Any]) -> dict[str, Any]:
    company_slug = slugify(company)
    query_terms = [
        f"{company} startup funding founders Crunchbase",
        f"{company} startup competitors market traction",
        f"{company} company website press customers product",
        f"{company} startup revenue customers pilots partnerships",
        f"{company} founder background LinkedIn company profile",
        f"{company} startup investors accelerator seed round",
        f"{company} market size industry report competitors",
        f"{company} SEC public company comparables market multiple",
    ]
    templates = list(internet.get("source_url_templates") or DEFAULT_SOURCE_URL_TEMPLATES)
    target_urls = [template.format(company=company, company_slug=company_slug) for template in templates]
    return {
        "company": company,
        "company_slug": company_slug,
        "queries": query_terms[: int(internet.get("max_queries") or 3)],
        "target_urls": target_urls,
        "verification_domains": list(internet.get("verification_domains") or DEFAULT_VERIFICATION_DOMAINS),
        "verification_fields": list(
            internet.get("verification_fields")
            or [
                "company_profile",
                "founders",
                "funding",
                "category",
                "competitors",
                "traction_claims",
                "source_conflicts",
            ]
        ),
        "privacy_policy": "Queries use company names and public descriptors only; confidential document excerpts are blocked.",
    }

def infer_source_quality_label(status: str, skill: str, verification_target: str, url: str, snippet: str) -> str:
    lowered_status = str(status or "").lower()
    lowered_skill = str(skill or "").lower()
    lowered_target = str(verification_target or "").lower()
    lowered_url = str(url or "").lower()
    lowered_snippet = str(snippet or "").lower()
    if lowered_status in {"blocked", "failed", "skill_unavailable", "budget_exhausted", "disabled"}:
        return "blocked"
    if lowered_status in {"planned", "configured_reference", "warning"}:
        return "thin_signal"
    if "financial_public_data_tool" in lowered_skill or any(domain in lowered_url for domain in ("sec.gov", "bls.gov", "sba.gov")):
        return "market_context"
    if "github.com" in lowered_url or any(term in lowered_target for term in ("github", "technical", "product")):
        return "technical_signal"
    if any(term in lowered_snippet for term in ("conflict", "contradict", "unconfirmed")):
        return "public_conflict"
    if lowered_url.startswith(("http://", "https://")) and lowered_status in {"ok", "completed"}:
        return "public_confirmation"
    return "thin_signal"

def _source_record(
    *,
    company: str | None = None,
    entity: str | None = None,
    query: str,
    url: str,
    title: str,
    snippet: str,
    status: str,
    skill: str,
    verification_target: str,
    warning: str = "",
    source_quality_label: str | None = None,
) -> dict[str, Any]:
    selected_entity = str(company or entity or "")
    snippet_limit = 10000 if skill == "financial_public_data_tool" else 1000
    quality = source_quality_label or infer_source_quality_label(status, skill, verification_target, url, snippet)
    return shared_source_record(
        entity=selected_entity,
        query=query,
        url=url,
        title=title or url.split("//", 1)[-1].split("/", 1)[0],
        snippet=snippet[:snippet_limit],
        status=status,
        skill=skill,
        verification_target=verification_target,
        warning=warning,
        retrieved_at=utc_now_iso(),
        source_quality_label=quality if quality in SOURCE_QUALITY_LABELS else "thin_signal",
    )

def _mock_public_source(
    *,
    company: str,
    query: str,
    skill: str,
    verification_target: str,
    url: str = "",
    title: str = "",
) -> dict[str, Any]:
    source = _source_record(
        company=company,
        query=query,
        url=url or f"https://mock.local/{slugify(company)}/{slugify(verification_target)}",
        title=title or f"Mock {verification_target.replace('_', ' ')} source for {company}",
        snippet=(
            f"Mock source generated by --fake-skills for {company}. "
            "It simulates public evidence so the VC Assistant workflow can exercise downstream scoring and reporting quickly."
        ),
        status="mocked",
        skill=skill,
        verification_target=verification_target,
        warning="fake_skills mock source; do not use for investment decisions",
        source_quality_label="thin_signal",
    )
    source["mocked"] = True
    return source

def _budget_exhausted_source(company: str, query: str, skill: str, verification_target: str, action_type: str) -> dict[str, Any]:
    source = shared_budget_exhausted_source(company, query, skill, verification_target, action_type)
    source.update(
        {
            "url": "action_budget",
            "title": "Action budget exhausted",
            "snippet": f"Skipped {action_type} because the VC Assistant action budget was exhausted.",
            "warning": "Action budget exhausted before this evidence source could be collected.",
        }
    )
    return source

_append_python_http_search = partial(
    shared_append_python_http_search,
    source_builder=_source_record,
    budget_exhausted_builder=_budget_exhausted_source,
    fetcher=_fetch_public_http,
)

_append_python_http_target_research = partial(
    shared_append_python_http_targets,
    source_builder=_source_record,
    budget_exhausted_builder=_budget_exhausted_source,
    fetcher=_fetch_public_http,
)

def _compact_text(value: Any, *, limit: int) -> str:
    text = redactor(str(value or "")).strip()
    compact = shared_compact_text(text, limit=limit)
    return compact if len(text) <= limit else compact.rstrip() + "...[truncated]"

def compact_local_evidence_for_transport(
    records: list[dict[str, Any]],
    *,
    limit: int = MAX_TRANSPORT_EVIDENCE_PER_COMPANY,
) -> list[dict[str, Any]]:
    compact_records = shared_compact_local_evidence_for_transport(
        records,
        limit=limit,
        text_limit=MAX_TRANSPORT_TEXT_PREVIEW_CHARS,
    )
    for item, record in zip(compact_records, records[:limit]):
        item.update(
            {
                "kind": "local_document_evidence",
                "suffix": record.get("suffix"),
                "sha256_prefix": str(record.get("sha256") or "")[:16],
                "extraction_method": record.get("extraction_method"),
                "ocr_required": bool(record.get("ocr_required")),
                "warnings": [_compact_text(warning, limit=240) for warning in (record.get("warnings") or [])[:5]],
            }
        )
    return compact_records

def compact_research_sources_for_transport(
    sources: list[dict[str, Any]],
    *,
    limit: int = MAX_TRANSPORT_SOURCES_PER_COMPANY,
) -> list[dict[str, Any]]:
    compact_sources = shared_compact_research_sources_for_transport(
        sources,
        limit=limit,
        snippet_limit=MAX_TRANSPORT_SNIPPET_CHARS,
    )
    for item, source in zip(compact_sources, sources[:limit]):
        item.update(
            {
                "company": source.get("company"),
                "query": _compact_text(source.get("query"), limit=360),
                "url": _compact_text(source.get("url"), limit=1000),
                "title": _compact_text(source.get("title"), limit=300),
                "warning": _compact_text(source.get("warning"), limit=500),
                "retrieved_at": source.get("retrieved_at"),
            }
        )
        for key in ("agent_id", "tool_call_id", "tool_decision_source", "fallback_after_agentic"):
            if source.get(key) is not None:
                item[key] = source.get(key)
    return compact_sources

def compact_company_report_for_transport(report: dict[str, Any]) -> dict[str, Any]:
    compact = {**shared_compact_company_report_for_transport(report), **dict(report)}
    evidence = report.get("evidence")
    if isinstance(evidence, list):
        compact["evidence"] = compact_local_evidence_for_transport(evidence)
    sources = report.get("research_sources")
    if isinstance(sources, list):
        compact["research_sources"] = compact_research_sources_for_transport(sources)
    return compact

def agentic_research_config(config: dict[str, Any]) -> dict[str, Any]:
    raw = config.get("agentic_research") if isinstance(config.get("agentic_research"), dict) else {}
    if quick_test_mode_enabled(config):
        return {
            "enabled": False,
            "agent_ids": [str(item) for item in (raw.get("agent_ids") or DEFAULT_AGENTIC_RESEARCH_AGENT_IDS)],
            "max_iterations_per_agent": 1,
            "max_tool_calls_per_agent": 0,
            "allowed_tools": [str(item) for item in (raw.get("allowed_tools") or DEFAULT_AGENTIC_RESEARCH_TOOLS)],
        }
    return {
        "enabled": bool(raw.get("enabled", False)),
        "agent_ids": [str(item) for item in (raw.get("agent_ids") or DEFAULT_AGENTIC_RESEARCH_AGENT_IDS)],
        "max_iterations_per_agent": bounded_int(raw.get("max_iterations_per_agent"), default=1, minimum=1, maximum=100),
        "max_tool_calls_per_agent": bounded_int(raw.get("max_tool_calls_per_agent"), default=2, minimum=0, maximum=500),
        "allowed_tools": [str(item) for item in (raw.get("allowed_tools") or DEFAULT_AGENTIC_RESEARCH_TOOLS)],
    }

def actor_review_config(config: dict[str, Any]) -> dict[str, Any]:
    raw = config.get("actor_review") if isinstance(config.get("actor_review"), dict) else {}
    memory = config.get("memory_layer") if isinstance(config.get("memory_layer"), dict) else {}
    conversation = memory.get("conversation") if isinstance(memory.get("conversation"), dict) else {}
    selected = raw.get("llm_actor_ids") if isinstance(raw.get("llm_actor_ids"), list) else DEFAULT_ACTOR_REVIEW_LLM_ACTOR_IDS
    return {
        "llm_actor_ids": [str(item) for item in selected],
        "max_context_chars": bounded_int(raw.get("max_context_chars"), default=6000, minimum=2000, maximum=50000),
        "use_context_engine": bool(raw.get("use_context_engine", raw.get("use_model_compression", conversation.get("use_model_compression", True)))),
        "working_memory_persist_to_redis": bool(raw.get("working_memory_persist_to_redis", False)),
        "context_token_budget": bounded_int(raw.get("context_token_budget"), default=conversation.get("token_budget") or DEFAULT_ACTOR_REVIEW_CONTEXT_TOKEN_BUDGET, minimum=500, maximum=20000),
        "context_target_tokens": bounded_int(raw.get("context_target_tokens"), default=conversation.get("target_tokens") or DEFAULT_ACTOR_REVIEW_CONTEXT_TARGET_TOKENS, minimum=200, maximum=8000),
    }

def _research_agent_enabled(agentic: dict[str, Any], agent_id: str) -> bool:
    return bool(agentic.get("enabled")) and agent_id in set(agentic.get("agent_ids") or [])

def _agent_tool_source(
    *,
    company: str,
    agent_id: str,
    query: str,
    status: str,
    message: str,
    tool_call_id: str = "",
) -> dict[str, Any]:
    record = _source_record(
        company=company,
        query=query,
        url="agent_tool_loop",
        title=f"{agent_id} tool loop",
        snippet=message,
        status=status,
        skill="llm_tool_agent",
        verification_target=agent_id,
        warning=message if status in {"agent_tool_loop_failed", "agent_invalid_tool_call", "agent_tool_call_failed", "blocked"} else "",
        source_quality_label="blocked" if status in {"agent_tool_loop_failed", "agent_invalid_tool_call", "agent_tool_call_failed", "blocked"} else "thin_signal",
    )
    record["agent_id"] = agent_id
    record["tool_call_id"] = tool_call_id
    record["tool_decision_source"] = "llm_agent"
    return record

def _annotate_agent_sources(sources: list[dict[str, Any]], start_index: int, *, agent_id: str, tool_call_id: str) -> None:
    shared_annotate_agent_sources(sources, start_index, agent_id=agent_id, tool_call_id=tool_call_id)
    for source in sources[start_index:]:
        source["tool_decision_source"] = "llm_agent"

def _blocked_tool_text(value: str, internet: dict[str, Any]) -> str:
    lowered = value.lower()
    blocked = [
        "raw document text",
        "confidential",
        "private financial",
        "customer names",
        "founder contact",
        "phone",
        "email",
    ]
    blocked.extend(str(item).replace("_", " ").lower() for item in (internet.get("blocked_inputs") or []))
    for marker in blocked:
        if marker and marker in lowered:
            return marker
    return ""

def _validate_agent_tool_call(tool_call: dict[str, Any], *, allowed_tools: set[str], internet: dict[str, Any]) -> str:
    shared_error = PublicResearchPolicy.from_mapping(
        allowed_tools=sorted(allowed_tools),
        internet=internet,
    ).validate(tool_call)
    if shared_error:
        return shared_error
    tool = str(tool_call.get("tool") or "")
    if tool not in allowed_tools:
        return f"Tool '{tool}' is not allowed for this agent."
    if tool == "finish":
        return ""
    query = str(tool_call.get("query") or "")
    url = str(tool_call.get("url") or "")
    if tool == "browser_search" and not query.strip():
        return "browser_search requires a query."
    if tool in {"browser_page", "rendered_browser_page"} and not url.startswith(("http://", "https://")):
        return f"{tool} requires an http(s) url."
    blocked = _blocked_tool_text(f"{query} {url}", internet)
    if blocked:
        return f"Tool call includes blocked private/confidential input marker: {blocked}."
    return ""

def _agent_observation_from_sources(sources: list[dict[str, Any]], start_index: int) -> dict[str, Any]:
    observation = shared_observation_from_sources(sources, start_index)
    added = sources[start_index:]
    observation["statuses"] = sorted({str(source.get("status") or "") for source in added if source.get("status")})
    observation["urls"] = [str(source.get("url") or "") for source in added[:5]]
    observation["snippets"] = [str(source.get("snippet") or "")[:240] for source in added[:3]]
    return observation

def _execute_agent_tool_call(
    *,
    sources: list[dict[str, Any]],
    company: str,
    stage: str,
    plan: dict[str, Any],
    internet: dict[str, Any],
    run_dir: Path | None,
    action_budget: ActionBudget | None,
    tool_call: dict[str, Any],
    tool_call_id: str,
) -> dict[str, Any]:
    # Imported lazily to keep the domain dependency direction acyclic: browser
    # adapters depend on the record/tool policy in this module.
    from .research_browser import (
        _append_browser_research,
        _append_rendered_browser_research,
        _append_target_url_research,
    )

    tool = str(tool_call.get("tool") or "")
    if tool == "finish":
        return {"status": "finished", "source_count": 0, "stop_reason": str(tool_call.get("reason") or "finish")}
    start_index = len(sources)
    tool_plan = dict(plan)
    query = str(tool_call.get("query") or (plan.get("queries") or [""])[0])
    url = str(tool_call.get("url") or "")
    tool_plan["queries"] = [query]
    if url:
        tool_plan["target_urls"] = [url]
    def browser_search(**_options: Any) -> None:
        call_with_supported_kwargs(
            _append_browser_research,
            sources=sources,
            company=company,
            plan=tool_plan,
            internet=internet,
            run_dir=run_dir,
            verification_target=stage,
            action_budget=action_budget,
        )

    def browser_page(**_options: Any) -> None:
        call_with_supported_kwargs(
            _append_target_url_research,
            sources=sources,
            company=company,
            plan=tool_plan,
            internet=internet,
            run_dir=run_dir,
            action_budget=action_budget,
        )

    def rendered_browser_page(**_options: Any) -> None:
        rendered_internet = dict(internet)
        rendered = dict(rendered_internet.get("rendered_browser") or {})
        rendered["enabled"] = True
        rendered_internet["rendered_browser"] = rendered
        call_with_supported_kwargs(
            _append_rendered_browser_research,
            sources=sources,
            company=company,
            plan=tool_plan,
            internet=rendered_internet,
            action_budget=action_budget,
        )

    PublicResearchToolset(
        tools={
            "browser_search": browser_search,
            "browser_page": browser_page,
            "rendered_browser_page": rendered_browser_page,
        },
        policy=PublicResearchPolicy.from_mapping(
            allowed_tools=["browser_search", "browser_page", "rendered_browser_page", "finish"],
            internet=internet,
        ),
    ).execute(tool_call)
    _annotate_agent_sources(sources, start_index, agent_id=stage, tool_call_id=tool_call_id)
    return {
        "status": "executed",
        **_agent_observation_from_sources(sources, start_index),
        "mocked": any(source.get("mocked") for source in sources[start_index:]),
    }

def _execute_agent_tool_plan(
    *,
    sources: list[dict[str, Any]],
    company: str,
    stage: str,
    plan: dict[str, Any],
    internet: dict[str, Any],
    run_dir: Path | None,
    action_budget: ActionBudget | None,
    iteration: int,
    decision: dict[str, Any],
    tool_calls: list[Any],
    allowed_tools: set[str],
    remaining_tool_calls: int,
) -> dict[str, Any]:
    validation_failures: list[dict[str, Any]] = []
    executed_records: list[dict[str, Any]] = []
    observations: list[dict[str, Any]] = []
    actions: list[ToolAction] = []
    for call_index, raw_call in enumerate(tool_calls, start=1):
        tool_call = raw_call if isinstance(raw_call, dict) else {"tool": ""}
        tool_call_id = f"{stage}-{iteration}-{call_index}"
        validation_error = _validate_agent_tool_call(
            tool_call,
            allowed_tools=allowed_tools,
            internet=internet,
        )
        if validation_error:
            sources.append(
                _agent_tool_source(
                    company=company,
                    agent_id=stage,
                    query=str(tool_call.get("query") or ""),
                    status="agent_invalid_tool_call",
                    message=validation_error,
                    tool_call_id=tool_call_id,
                )
            )
            if run_dir:
                append_event(
                    run_dir,
                    "tool_call_failed",
                    {
                        "tool": tool_call.get("tool"),
                        "agent_id": stage,
                        "tool_call_id": tool_call_id,
                        "company": company,
                        "error": validation_error,
                    },
                )
            failure = {
                "iteration": iteration,
                "tool_call_id": tool_call_id,
                "message": validation_error,
                "tool_call": tool_call,
            }
            validation_failures.append(failure)
            executed_records.append(
                {
                    "tool_call_id": tool_call_id,
                    "status": "invalid",
                    "message": validation_error,
                }
            )
            continue
        kind = "final" if str(tool_call.get("tool") or "") == "finish" else "tool"
        actions.append(
            ToolAction(
                name=str(tool_call.get("tool") or ""),
                arguments={
                    "tool_call": tool_call,
                    "tool_call_id": tool_call_id,
                },
                kind=kind,
            )
        )

    def execute_tool(_context: Any, action: ToolAction, **_options: Any) -> dict[str, Any]:
        tool_call = dict(action.arguments.get("tool_call") or {})
        tool_call_id = str(action.arguments.get("tool_call_id") or "")
        if run_dir:
            append_event(
                run_dir,
                "tool_call_started",
                {
                    "tool": action.name,
                    "agent_id": stage,
                    "tool_call_id": tool_call_id,
                    "company": company,
                },
            )
        with observed_operation(
            run_dir,
            phase="public_tool_call",
            operation=action.name or "unknown_tool",
            company=company,
            agent_id=stage,
            tool_call_id=tool_call_id,
            query_hash=stable_text_hash(tool_call.get("query") or ""),
            query_chars=len(str(tool_call.get("query") or "")),
            url_host=host_from_url(str(tool_call.get("url") or "")) if tool_call.get("url") else "",
        ) as op:
            try:
                result = _execute_agent_tool_call(
                    sources=sources,
                    company=company,
                    stage=stage,
                    plan=plan,
                    internet=internet,
                    run_dir=run_dir,
                    action_budget=action_budget,
                    tool_call=tool_call,
                    tool_call_id=tool_call_id,
                )
            except Exception as exc:
                result = {"status": "failed", "source_count": 0, "error": str(exc)}
                sources.append(
                    _agent_tool_source(
                        company=company,
                        agent_id=stage,
                        query=str(tool_call.get("query") or ""),
                        status="agent_tool_call_failed",
                        message=str(exc),
                        tool_call_id=tool_call_id,
                    )
                )
            op.close(
                "completed" if result.get("status") in {"executed", "finished"} else "failed",
                tool_status=result.get("status"),
                source_count=result.get("source_count"),
                error=result.get("error"),
                mocked=bool(result.get("mocked")),
            )
        observation = {"tool_call_id": tool_call_id, "tool": action.name, "result": result}
        observations.append(observation)
        executed_records.append(
            {
                "tool_call_id": tool_call_id,
                "tool": action.name,
                "status": result.get("status"),
            }
        )
        if run_dir:
            event_type = "tool_call_completed" if result.get("status") in {"executed", "finished"} else "tool_call_failed"
            append_event(
                run_dir,
                event_type,
                {
                    "tool": action.name,
                    "agent_id": stage,
                    "tool_call_id": tool_call_id,
                    "company": company,
                    "result": result,
                },
            )
        return result

    stop_reason = (
        "agent_invalid_tool_call"
        if not actions and validation_failures
        else str(decision.get("stop_reason") or "")
        if any(action.kind == "final" for action in actions)
        else ""
    )
    bounded = create_bounded_tool_loop(
        ToolLoopSpec(
            propose_action=lambda _context, _trace, **_options: ToolPlan(
                actions=tuple(actions),
                metadata={
                    "thought_summary": str(decision.get("thought_summary") or "")[:500],
                    "evidence_gaps": list(decision.get("evidence_gaps") or [])[:10]
                    if isinstance(decision.get("evidence_gaps"), list)
                    else [],
                },
                stop_reason=stop_reason,
            ),
            execute_action=execute_tool,
            max_iterations=1,
            max_tool_calls=max(0, remaining_tool_calls),
        )
    )({})
    bounded_stop_reason = str(bounded.get("stop_reason") or "")
    return {
        "validation_failures": validation_failures,
        "executed_tool_calls": executed_records,
        "observations": observations,
        "tool_call_count": int(bounded.get("tool_calls") or 0),
        "finished": any(record.get("kind") == "final" for record in bounded.get("trace") or []),
        "stop_reason": "max_tool_calls_reached"
        if bounded_stop_reason == "tool_call_budget_exhausted"
        else bounded_stop_reason,
        "bounded_trace": bounded.get("trace") or [],
    }

def _default_agent_tool_response(agent_id: str, plan: dict[str, Any], observations: list[dict[str, Any]]) -> dict[str, Any]:
    if observations:
        return {
            "thought_summary": "Existing observations are sufficient for this bounded pass.",
            "tool_calls": [{"tool": "finish", "reason": "observations_collected"}],
            "stop_reason": "observations_collected",
            "evidence_gaps": [],
        }
    query = (plan.get("agent_queries") or {}).get(agent_id, []) or plan.get("queries") or []
    urls = (plan.get("agent_target_urls") or {}).get(agent_id, []) or []
    if agent_id == "rendered_page_researcher":
        urls = plan.get("rendered_target_urls") or urls
    if urls and agent_id in {"company_identity_researcher", "market_comp_researcher", "traction_verifier"}:
        return {
            "thought_summary": "Inspect a known public URL selected by the adaptive plan.",
            "tool_calls": [{"tool": "browser_page", "url": urls[0], "query": query[0] if query else ""}],
            "stop_reason": "",
            "evidence_gaps": [],
        }
    if urls and agent_id == "rendered_page_researcher":
        return {
            "thought_summary": "Inspect a rendered public profile URL selected by the adaptive plan.",
            "tool_calls": [{"tool": "rendered_browser_page", "url": urls[0], "query": query[0] if query else ""}],
            "stop_reason": "",
            "evidence_gaps": [],
        }
    return {
        "thought_summary": "Run one broad public search selected by the adaptive plan.",
        "tool_calls": [{"tool": "browser_search", "query": query[0] if query else f"{plan.get('company', '')} startup public evidence"}],
        "stop_reason": "",
        "evidence_gaps": [],
    }

def _research_agent_plan_record(company: str, agent_id: str, query: str, plan: dict[str, Any]) -> dict[str, Any]:
    selected_lanes = [
        lane["lane_id"]
        for lane in plan.get("lanes", [])
        if query in (lane.get("queries") or [])
    ]
    return _source_record(
        company=company,
        query=query,
        url="research_plan",
        title=f"{agent_id.replace('_', ' ').title()} Query",
        snippet=f"Verification fields: {', '.join(plan.get('verification_fields') or [])}; selected lanes: {', '.join(selected_lanes) if selected_lanes else 'baseline'}",
        status="planned",
        skill="research_planner",
        verification_target=agent_id,
        source_quality_label="thin_signal",
    )

normalized_research_ledger = partial(
    shared_normalize_research_ledger,
    stage_ids=RESEARCH_AGENT_IDS,
    include_unknown_stages=False,
)
