"""Startup packet intake, grouping, fingerprints, and cache policy."""

from __future__ import annotations

from .common import *

def slugify(value: str) -> str:
    from mn_sdk.blueprint_support import slugify as shared_slugify

    return shared_slugify(value)

def redactor(text: str) -> str:
    return redact_common_pii(text)

class OcrRequiredError(RuntimeError):
    pass

def startup_packet_classifier(text: str, filename: str) -> str:
    del text, filename
    return "startup_packet"

def _document_paths(folder: Path) -> list[Path]:
    if not folder.exists():
        return []
    return shared_document_paths(folder, supported_suffixes=SUPPORTED_SUFFIXES)

def _path_key(path: Path) -> str:
    return str(path.expanduser().resolve())

def _llm_ocr_records_for_pdfs(folder: Path, pdf_paths: list[Path], config: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
    if not pdf_paths:
        return {}
    if fake_skills_mode_enabled(config):
        records_by_path: dict[str, dict[str, Any]] = {}
        for path in pdf_paths:
            company = infer_company_name(path, path.stem, folder)
            records_by_path[_path_key(path)] = {
                "path": str(path),
                "text": (
                    f"Company: {company}\n"
                    "Mock OCR text generated by --fake-skills for blueprint logic testing.\n"
                    "Product: AI workflow automation platform.\n"
                    "Market: enterprise productivity and startup operations.\n"
                    "Traction: pilot customers, early revenue signals, and active founder-led sales.\n"
                    "Risks: mock source data must be replaced with real document extraction before investment decisions.\n"
                ),
                "warnings": ["fake_skills mock OCR record"],
                "extraction_method": "fake_llm_ocr_skill",
                "ocr_required": False,
                "mocked": True,
            }
        return records_by_path
    if extract_document_folder is None:
        raise OcrRequiredError("PDF startup packets require llm_ocr_skill, but the OCR extractor is unavailable.")

    resolved_pdf_keys = {_path_key(path) for path in pdf_paths}
    skill_config = {"input_skills": (config or {}).get("input_skills", {})}
    ocr_config = ((config or {}).get("input_skills") or {}).get("llm_ocr") or {}
    min_text_chars = int(ocr_config.get("min_text_chars") or 40)
    factory = docker_ocr_client_factory_from_config(skill_config) if docker_ocr_client_factory_from_config else None
    records_by_path: dict[str, dict[str, Any]] = {}

    for parent in sorted({path.parent for path in pdf_paths}):
        try:
            extracted_records = extract_document_folder(
                parent,
                classifier=startup_packet_classifier,
                redactor=redactor,
                llm_ocr_client_factory=factory,
                min_text_chars=min_text_chars,
            )
        except Exception as exc:
            raise OcrRequiredError(f"PDF OCR failed for {parent}: {exc}") from exc

        for record in extracted_records:
            raw_path = record.get("path")
            if not raw_path:
                continue
            key = _path_key(Path(str(raw_path)))
            if key in resolved_pdf_keys:
                records_by_path[key] = dict(record)

    missing = [str(path) for path in pdf_paths if _path_key(path) not in records_by_path]
    if missing:
        raise OcrRequiredError(f"PDF OCR returned no evidence for required input(s): {', '.join(missing)}")

    for path in pdf_paths:
        record = records_by_path[_path_key(path)]
        text = str(record.get("text") or "")
        warnings = record.get("warnings") if isinstance(record.get("warnings"), list) else []
        if bool(record.get("ocr_required")) or len(text.strip()) < min_text_chars:
            detail = "; ".join(str(warning) for warning in warnings if warning) or "OCR returned too little text."
            raise OcrRequiredError(f"PDF OCR did not produce usable text for {path}: {detail}")

    return records_by_path

def infer_company_name(path: Path, text: str, root: Path) -> str:
    try:
        relative = path.relative_to(root)
    except ValueError:
        relative = path
    if len(relative.parts) > 1:
        return relative.parts[0].replace("_", " ").replace("-", " ").title()
    return infer_group_name(
        path,
        text,
        root,
        label_pattern=r"(?im)^\s*(company|startup)\s*[:\-]\s*(.+?)\s*$",
    )[:80]

def scan_documents(folder: Path, config: dict[str, Any] | None = None) -> dict[str, list[dict[str, Any]]]:
    records_by_company: dict[str, list[dict[str, Any]]] = {}
    paths = _document_paths(folder)
    if not paths:
        return records_by_company
    pdf_paths = [path for path in paths if path.suffix.lower() == ".pdf"]
    ocr_records_by_path = _llm_ocr_records_for_pdfs(folder, pdf_paths, config)
    for path in paths:
        suffix = path.suffix.lower()
        if suffix in TEXT_SUFFIXES:
            text, warnings = safe_read_text(path)
            extraction_method = "embedded_text"
            ocr_required = False
        else:
            ocr_record = ocr_records_by_path[_path_key(path)]
            text = str(ocr_record.get("text") or "")
            raw_warnings = ocr_record.get("warnings")
            warnings = [str(warning) for warning in raw_warnings] if isinstance(raw_warnings, list) else []
            extraction_method = str(ocr_record.get("extraction_method") or "llm_ocr")
            ocr_required = bool(ocr_record.get("ocr_required"))
        redacted = redactor(text)
        company = infer_company_name(path, redacted, folder)
        digest = file_sha256(path)
        record = {
            "path": str(path),
            "filename": path.name,
            "company_name": company,
            "sha256": digest,
            "suffix": suffix,
            "text_preview": redacted[:1200],
            "character_count": len(redacted),
            "extraction_method": extraction_method,
            "ocr_required": ocr_required,
            "warnings": warnings,
        }
        records_by_company.setdefault(company, []).append(record)
    return records_by_company

def company_fingerprint(records: list[dict[str, Any]]) -> str:
    return records_fingerprint(records)

def load_watch_state(output_folder: Path) -> dict[str, Any]:
    state = read_json(output_folder / "watch_state.json")
    companies = state.get("companies")
    if not isinstance(companies, dict):
        state["companies"] = {}
    return state

def force_reprocess_enabled(payload: dict[str, Any], config: dict[str, Any]) -> bool:
    cache_config = config.get("cache_policy") if isinstance(config.get("cache_policy"), dict) else {}
    payload_policy = payload.get("cache_policy") if isinstance(payload.get("cache_policy"), dict) else {}
    candidates = [
        payload.get("force_reprocess"),
        payload.get("force_refresh"),
        payload_policy.get("force_reprocess"),
        cache_config.get("force_reprocess"),
    ]
    if any(str(value).strip().lower() in {"1", "true", "yes", "on"} for value in candidates if value is not None):
        return True
    return any(env_flag_enabled(name) for name in ("VC_ASSISTANT_FORCE_REPROCESS", "MN_BLUEPRINT_FORCE_REPROCESS", "MN_FORCE_REPROCESS"))

def build_company_work_queue(company_records: dict[str, list[dict[str, Any]]], previous_state: dict[str, Any], *, force_reprocess: bool = False) -> list[dict[str, Any]]:
    previous_companies = previous_state.get("companies") if isinstance(previous_state.get("companies"), dict) else {}
    queue = []
    for company, records in sorted(company_records.items(), key=lambda item: slugify(item[0])):
        slug = slugify(company)
        fingerprint = company_fingerprint(records)
        previous = previous_companies.get(slug) if isinstance(previous_companies.get(slug), dict) else {}
        unchanged = previous.get("fingerprint") == fingerprint
        use_cached = unchanged and not force_reprocess
        previous_run_id = previous.get("last_run_id") or previous_state.get("run_id")
        cache_policy = {
            "company_slug": slug,
            "fingerprint": fingerprint,
            "previous_fingerprint": previous.get("fingerprint"),
            "previous_run_id": previous_run_id,
            "cache_source": "watch_state_and_company_artifacts" if use_cached else "",
            "freshness": "unchanged_cached" if use_cached else ("forced_reprocess" if force_reprocess and unchanged else "fresh_or_changed"),
            "force_reprocess": bool(force_reprocess),
            "decision": "reuse_cached_outputs" if use_cached else "process_company_packet",
        }
        queue.append(
            {
                "company_id": slug,
                "company_name": company,
                "company_slug": slug,
                "fingerprint": fingerprint,
                "document_count": len(records),
                "status": "unchanged_skipped" if use_cached else "new_or_changed",
                "previous_fingerprint": previous.get("fingerprint"),
                "previous_run_id": previous_run_id,
                "cache_policy": cache_policy,
                "source_refs": [record.get("path") for record in records],
            }
        )
    return queue

def update_watch_state(output_folder: Path, run_dir: Path, queue: list[dict[str, Any]], *, run_id: str) -> dict[str, Any]:
    state = {
        "run_id": run_id,
        "updated_at": utc_now_iso(),
        "companies": {
            item["company_slug"]: {
                "company_name": item["company_name"],
                "fingerprint": item["fingerprint"],
                "status": item["status"],
                "document_count": item["document_count"],
                "last_run_id": run_id,
            }
            for item in queue
        },
    }
    write_json(output_folder / "watch_state.json", state)
    write_json(run_dir / "watch_state.json", state)
    return state

def load_cached_company_analysis(output_folder: Path, company: str) -> dict[str, Any] | None:
    analysis = read_json(output_folder / slugify(company) / "analysis.json")
    if analysis.get("company_name") != company:
        return None
    if not isinstance(analysis.get("methods"), dict):
        return None
    return analysis

def load_cached_research_ledger(output_folder: Path, company: str) -> dict[str, list[dict[str, Any]]] | None:
    ledger = read_json(output_folder / "research_ledgers" / f"{slugify(company)}.json")
    if not ledger:
        return None
    normalized: dict[str, list[dict[str, Any]]] = {}
    for stage in RESEARCH_AGENT_IDS:
        values = ledger.get(stage)
        normalized[stage] = values if isinstance(values, list) else []
    return normalized

def build_cache_policy_summary(queue: list[dict[str, Any]], *, processed_company_names: list[str], skipped_company_names: list[str]) -> dict[str, Any]:
    force_reprocess = any(bool((item.get("cache_policy") or {}).get("force_reprocess")) for item in queue)
    return {
        "enabled": True,
        "force_reprocess": force_reprocess,
        "processed_company_count": len(processed_company_names),
        "skipped_company_count": len(skipped_company_names),
        "fresh_run": len(skipped_company_names) == 0,
        "companies": [
            {
                "company_name": item.get("company_name"),
                "company_slug": item.get("company_slug"),
                "status": item.get("status"),
                "fingerprint": item.get("fingerprint"),
                "previous_fingerprint": item.get("previous_fingerprint"),
                "previous_run_id": item.get("previous_run_id"),
                "cache_source": (item.get("cache_policy") or {}).get("cache_source"),
                "freshness": (item.get("cache_policy") or {}).get("freshness"),
                "decision": (item.get("cache_policy") or {}).get("decision"),
            }
            for item in queue
        ],
    }

def group_document_file_records(document_folder: Path, files: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    return shared_group_document_file_records(document_folder, files)

def processed_and_skipped_company_names(company_work_queue: list[dict[str, Any]]) -> tuple[list[str], list[str]]:
    processed = [str(item["company_name"]) for item in company_work_queue if item.get("status") != "unchanged_skipped"]
    skipped = [str(item["company_name"]) for item in company_work_queue if item.get("status") == "unchanged_skipped"]
    return processed, skipped
