from __future__ import annotations

from .cli_runtime import build_cli_parser, run_blueprint_cli
from .config import config_summary, default_config, load_config, validate_config
from .constants import (
    BLUEPRINT_CATEGORIES,
    CONFIG_SECTIONS,
    DEFAULT_BLUEPRINT_LOG_PATH,
    DEFAULT_LOGS_ROOT,
    DEFAULT_MN_HOME,
    DEFAULT_RUNS_ROOT,
    DEFAULT_USER_CONFIG_PATH,
    EXECUTION_MODEL,
    INPUT_ADAPTERS,
    OUTPUT_ADAPTERS,
    OPTIONAL_RUN_ARTIFACTS,
    RUN_ARTIFACTS,
    STANDARD_VERSION,
    WEB_UI_ADAPTERS,
)
from .input_adapters import resolve_input_overrides
from .metadata import BlueprintMetadata, infer_category
from .observability import list_runs, load_run, read_run_events, summarize_run
from .python_workflow_bundle import (
    PythonWorkflowBundleSpec,
    build_python_workflow_bundle_parser,
    build_source_python_workflow_bundle_parser,
    generate_python_workflow_bundle_from_blueprint_dir,
    generate_python_workflow_bundle,
    python_workflow_spec_from_blueprint_dir,
    run_python_workflow_bundle_cli,
    run_source_python_workflow_bundle_cli,
)
from .run_store import RunStore
from .runtime import BlueprintRuntimeContext, architecture_contract, create_runtime_context, resolve_output_adapter
from .scaffold import scaffold_blueprint
from .user_config import (
    UserConfigStore,
    default_user_config,
    interactive_first_run_setup,
    load_user_config,
    save_user_config,
    user_config_path,
)
from .utils import deep_merge, make_run_id, utc_now_iso
from .validation import validate_blueprint_directory
from .web_ui import (
    WebUIDependencyError,
    WebUIHandle,
    WebInputField,
    collect_gradio_input,
    custom_web_ui_handle,
    default_web_ui_config,
    launch_gradio_input_app,
    load_web_ui,
    maybe_write_static_output,
    register_web_ui,
    render_static_run_report,
    validate_web_ui_config,
    write_static_run_report,
)
from .worker_contract import (
    WorkerRunContract,
    create_worker_run_contract,
    create_worker_run_contract_from_environment,
    disabled_worker_run_contract,
)


__all__ = [
    "CONFIG_SECTIONS",
    "DEFAULT_BLUEPRINT_LOG_PATH",
    "DEFAULT_LOGS_ROOT",
    "DEFAULT_MN_HOME",
    "DEFAULT_RUNS_ROOT",
    "DEFAULT_USER_CONFIG_PATH",
    "EXECUTION_MODEL",
    "INPUT_ADAPTERS",
    "OUTPUT_ADAPTERS",
    "OPTIONAL_RUN_ARTIFACTS",
    "RUN_ARTIFACTS",
    "STANDARD_VERSION",
    "WEB_UI_ADAPTERS",
    "BLUEPRINT_CATEGORIES",
    "BlueprintMetadata",
    "BlueprintRuntimeContext",
    "RunStore",
    "UserConfigStore",
    "WebUIDependencyError",
    "WebUIHandle",
    "WebInputField",
    "WorkerRunContract",
    "PythonWorkflowBundleSpec",
    "architecture_contract",
    "build_cli_parser",
    "build_python_workflow_bundle_parser",
    "build_source_python_workflow_bundle_parser",
    "collect_gradio_input",
    "config_summary",
    "create_runtime_context",
    "create_worker_run_contract",
    "create_worker_run_contract_from_environment",
    "deep_merge",
    "default_config",
    "default_user_config",
    "default_web_ui_config",
    "disabled_worker_run_contract",
    "custom_web_ui_handle",
    "infer_category",
    "generate_python_workflow_bundle",
    "generate_python_workflow_bundle_from_blueprint_dir",
    "interactive_first_run_setup",
    "launch_gradio_input_app",
    "list_runs",
    "load_config",
    "load_run",
    "load_user_config",
    "load_web_ui",
    "make_run_id",
    "maybe_write_static_output",
    "read_run_events",
    "python_workflow_spec_from_blueprint_dir",
    "register_web_ui",
    "render_static_run_report",
    "resolve_input_overrides",
    "resolve_output_adapter",
    "run_blueprint_cli",
    "run_python_workflow_bundle_cli",
    "run_source_python_workflow_bundle_cli",
    "save_user_config",
    "scaffold_blueprint",
    "summarize_run",
    "utc_now_iso",
    "user_config_path",
    "validate_blueprint_directory",
    "validate_config",
    "validate_web_ui_config",
    "write_static_run_report",
]
